version: '3'
services:
  mysql:
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'micromeros'
      MYSQL_DATABASE: "testedb"
    ports:
      - 3307:3306
    volumes:
      - my-db:/var/lib/mysql
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  haproxy:
    image: haproxy:1.9-alpine
    ports:
      - 80:80
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
volumes:
  my-db:
